global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - api_url: '{{ $env.SLACK_API_URL }}'
      channel: '#monitoring-session'
      send_resolved: true
