version: '3.8'

services:
  backend:
    image: ryanleetecheer/backend-test:1.0.5
    container_name: backend
    restart: always
    ports:
      - '8000:8000'
    networks:
      - app-network

  frontend:
    image: ryanleetecheer/frontend-test:1.0.2
    container_name: front
    ports:
      - "5173:5173"
    command: yarn dev --host
    restart: always

networks:
  app-network:
    driver: bridge
