global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs:
      - targets: ['prometheus-example:9090']
  # - job_name: 'backend-data'
  #   static_configs:
  #     - targets: ['backend:8000']
  # - job_name: 'frontend-data'
  #   static_configs:
  #     - targets: ['frontend:5173']