global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs:
      - targets: ['prometheus-example:9090']
  - job_name: 'cadvisor-data'
    static_configs:
      - targets: ['cadvisor-example:8080']
  - job_name: 'node-exporter-data'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'nginx-exporter-data'
    static_configs:
      - targets: ['nginx-exporter:9113']
  # - job_name: 'backend-data'
  #   static_configs:
  #     - targets: ['backend:8000']
