global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs:
      - targets: ['prometheus-example:9090']
  - job_name: 'cadvisor-data'
    static_configs:
      - targets: ['cadvisor-example:8080']
  - job_name: 'node-data'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'nginx-data'
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'fastapi-data'
    static_configs:
      - targets: ['fastapi:8000']
  - job_name: 'mysql-data'
    static_configs:
      - targets: ['mysql-exporter:9104']
  - job_name: 'express-data'
    static_configs:
      - targets: ['express:3001']
  - job_name: 'django-data'
    static_configs:
      - targets: ['django:8002']
  - job_name: 'celery-data'
    static_configs:
      - targets: ['celery-worker:5555']
  - job_name: 'rabbitmq-data'
    static_configs:
      - targets: ['rabbitmq-example:15692']
  - job_name: 'redis-data'
    static_configs:
      - targets: ['redis-exporter:9121']
